dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.24.0/bazel_0.24.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.24.0-linux-x86_64.deb

script:
- cd src
- bazel test //test:unittest
- bazel coverage --instrumentation_filter=// //test:unittest
- bazel coverage --instrumentation_filter=// //test:perftest

after_success:
- cp bazel-testlogs/test/unittest/coverage.dat .
- bash <(curl -s https://codecov.io/bash)
